id: IAFAFEB99
ocr_import_info:
  timestamp: '2023-05-30T06:57:54.695030+00:00'
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.8
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-05-30 08:38:20.589864+00:00
last_modified: 2023-05-30 08:38:20.589872+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W23447
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW23447
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ངེས་དོན་ཕྱག་རྒྱ་ཆེན་པོའི་ཁྲིད་མཛོད།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.9771516542581411
  ocr_word_median_confidence_index: 0.999928
bases:
  I1896:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1896
      total_pages: 491
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1896.txt
    statistics:
      ocr_word_median_confidence_index: 0.9979485
      ocr_word_mean_confidence_index: 0.9643354804450988
  I1899:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1899
      total_pages: 403
      volume_number: 9
      volume_pages_bdrc_intro: 2
    order: 9
    base_file: I1899.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999145
      ocr_word_mean_confidence_index: 0.9747287418631378
  I1895:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1895
      total_pages: 396
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1895.txt
    statistics:
      ocr_word_median_confidence_index: 0.9973903
      ocr_word_mean_confidence_index: 0.9653098016200964
  I1894:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1894
      total_pages: 717
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1894.txt
    statistics:
      ocr_word_median_confidence_index: 0.99992985
      ocr_word_mean_confidence_index: 0.9819255687896866
  I1892:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1892
      total_pages: 851
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1892.txt
    statistics:
      ocr_word_median_confidence_index: 0.99999714
      ocr_word_mean_confidence_index: 0.9843620647052556
  I1900:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1900
      total_pages: 305
      volume_number: 10
      volume_pages_bdrc_intro: 2
    order: 10
    base_file: I1900.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999851
      ocr_word_mean_confidence_index: 0.9844273349494357
  I1897:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1897
      total_pages: 397
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1897.txt
    statistics:
      ocr_word_median_confidence_index: 0.9988578
      ocr_word_mean_confidence_index: 0.9677613685685084
  I1891:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1891
      total_pages: 697
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1891.txt
    statistics:
      ocr_word_median_confidence_index: 0.99975127
      ocr_word_mean_confidence_index: 0.9704269852599385
  I1903:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1903
      total_pages: 415
      volume_number: 13
      volume_pages_bdrc_intro: 2
    order: 13
    base_file: I1903.txt
    statistics:
      ocr_word_median_confidence_index: 0.999929
      ocr_word_mean_confidence_index: 0.9773859559407071
  I1898:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1898
      total_pages: 766
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1898.txt
    statistics:
      ocr_word_median_confidence_index: 0.99999934
      ocr_word_mean_confidence_index: 0.9877219730706589
  I1902:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1902
      total_pages: 420
      volume_number: 12
      volume_pages_bdrc_intro: 2
    order: 12
    base_file: I1902.txt
    statistics:
      ocr_word_median_confidence_index: 0.99955195
      ocr_word_mean_confidence_index: 0.976254709744601
  I1901:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1901
      total_pages: 612
      volume_number: 11
      volume_pages_bdrc_intro: 2
    order: 11
    base_file: I1901.txt
    statistics:
      ocr_word_median_confidence_index: 0.999972
      ocr_word_mean_confidence_index: 0.9805314332842139
  I1893:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1893
      total_pages: 987
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1893.txt
    statistics:
      ocr_word_median_confidence_index: 0.99997777
      ocr_word_mean_confidence_index: 0.979212945396847
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
